# Generated by Django 6.0.1 on 2026-01-14 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.CharField(db_index=True, max_length=40, unique=True)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('url', models.URLField()),
                ('raw_diff', models.TextField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('total_xp_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255, unique=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret from GitHub Webhook settings', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JudgeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_type', models.CharField(choices=[('ARCHITECT', 'The Architect (Complexity)'), ('PALADIN', 'The Paladin (Security)'), ('SCRIBE', 'The Scribe (Syntax/Style)')], max_length=20)),
                ('xp_awarded', models.IntegerField()),
                ('reasoning', models.TextField()),
                ('opik_trace_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='brain.commitlog')),
            ],
        ),
        migrations.AddField(
            model_name='commitlog',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='brain.repository'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(db_index=True, max_length=100, unique=True)),
                ('total_xp', models.IntegerField(default=0)),
                ('current_level', models.IntegerField(default=1)),
                ('current_streak', models.IntegerField(default=0)),
                ('last_commit_date', models.DateTimeField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(default='Novice Coder', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='brain.userprofile'),
        ),
    ]
