# Generated by Django 5.2.10 on 2026-03-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0004_alter_commitlog_id_alter_judgeevaluation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='webhook_secret',
        ),
    ]
